#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-2.0-or-later OR MIT

START=95
boot() {
	[ "$FAILSAFE" = "1" ] && return

	. /lib/functions.sh
	case $(board_name) in
	iodata,hdl-a|\
	iodata,hdl2-a)
		echo "on" > "/sys/devices/platform/landisk-r8c/leds-landisk-r8c/status_mode"
		;;
	esac
}
